# Generated by Django 5.0.3 on 2024-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dak_ticket', '0005_rename_type_event_event_type_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
