# Generated by Django 5.0.3 on 2024-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dak_ticket', '0006_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
